version: "3"
services:
  disburser-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:      
      VIRTUAL_HOST: wstest.mastertoco.de
      VIRTUAL_PORT: 8010
      LETSENCRYPT_HOST: wstest.mastertoco.de
    #ports:
    #  - "3008:3008"
    networks:
    - nginx-proxy

networks:
  nginx-proxy:
    external: true
